import ollama
import re

REPORT_PATH = 'reports/sadc_ministerial_brief.txt'

PROMPT_TEMPLATE = '''
You are an expert macro-fiscal policy analyst. Your task is to generate a concise, policy-focused executive summary for the SADC Ministerial Brief, based on the following appendix for {country_code}.

Appendix for {country_code}:
{appendix_text}

Instructions:
- Structure your summary with the following sections, using clear section headers:
    1. Risk Profile
    2. Key Trends
    3. Policy Implications
    4. Conclusion
- Do NOT include any tables, bullet lists, or code blocks. Only use paragraphs and section headers.
- Summarize key macro-fiscal risks, trends, and policy recommendations.
- Highlight data quality issues and structural breaks if relevant.
- Use clear, actionable language suitable for Ministers of Finance and Central Bank Governors.
- Keep the summary under 250 words.
- Do not repeat table content; synthesize insights.

Executive Summary:
'''




def extract_appendices(report_text):
    # Split by appendix section
    sections = re.findall(r'Appendix: (\w+)\n(.*?)(?=\n=+|$)', report_text, re.DOTALL)
    return {country: appendix.strip() for country, appendix in sections}

def replace_summaries(report_text, summaries):
    # Executive summaries only
    pattern = re.compile(r'(Ollama Executive Summary: (\w+)[ \t]*\n=+\n)[ \t]*\[This section will be generated by the Ollama agent based on the appendix above.\][ \t]*', re.MULTILINE)
    def full_repl(match):
        header = match.group(1)
        country = match.group(2)
        summary = summaries.get(country, '[Summary generation failed.]')
        return f'{header}{summary}\n'
    text = pattern.sub(full_repl, report_text)
    return text

def generate_summary(country_code, appendix_text):
    prompt = PROMPT_TEMPLATE.format(country_code=country_code, appendix_text=appendix_text)
    response = ollama.chat(model='gpt-oss:120b-cloud', messages=[{'role': 'user', 'content': prompt}])
    return response['message']['content']



if __name__ == '__main__':
    with open(REPORT_PATH, 'r', encoding='utf-8') as f:
        report_text = f.read()
    appendices = extract_appendices(report_text)
    summaries = {}
    for country, appendix in appendices.items():
        print(f'Generating summary for {country}...')
        summaries[country] = generate_summary(country, appendix)
    updated_text = replace_summaries(report_text, summaries)
    with open(REPORT_PATH, 'w', encoding='utf-8') as f:
        f.write(updated_text)
    print('Executive summaries inserted into sadc_ministerial_brief.txt.')
